### ISSUE TITLE
GatewayWorker这个是无效的吗？

### ISSUE THREAD

**Issue by ttyob** [top-think/think-worker#18]
我单独拿出来用，无法使用
----------------------- WORKERMAN -----------------------------
Workerman version:3.5.13          PHP version:7.0.19
------------------------ WORKERS -------------------------------
user          worker        listen        processes status
----------------------------------------------------------------
Press Ctrl+C to stop. Start success.

**Comment by liu21st** [comment]
你怎么用的？

**Comment by ttyob** [comment]
可以了，版本问题，坑人的国内composer镜像
