### ISSUE TITLE
print_r输出问题

### ISSUE THREAD

**Issue by lobtao** [top-think/think-worker#20]
function sqlite(){
        print_r($_SERVER);
        $ds = Db::query('select EmployeeID,FirstName,LastName from Employees');
        return $this->fetch('sqlite',[
            'data'=>$ds
        ]);
    }

sqlite里print_r输出data变量，但页面上会显示$_SERVER的值，按理$_SERVER的值是打印在控制台

**Comment by augushong** [comment]
如果在控制器结束时使用了类似return ''的样子,那么echo,dump等输出会输出到页面上,如果return response(''),json($data)等,打印的东西会输出到控制台.
可以试验一下
