### ISSUE TITLE
无法运行，按照官方手册直接运行是提示命名空间已被占用。

### ISSUE THREAD

**Issue by eliduty** [top-think/think-worker#22]
现象：在使用think-worker v2.0.11 按照官方手册安装后直接运行提示命名空间已被占用，如下图：
![image](https://user-images.githubusercontent.com/13143017/49713046-287c8f80-fc82-11e8-85ce-e6a2dc10ae84.png)
原因：注册命令顺序的问题。在v2.0.10版本使用正常 v2.0.11出现异常。需要调整命令注册的顺序，文件路径：vender/topthink/think-worker/src/command.php 
将
![image](https://user-images.githubusercontent.com/13143017/49713397-7776f480-fc83-11e8-8af3-0243cc6de39f.png)
改成
![image](https://user-images.githubusercontent.com/13143017/49713418-8c538800-fc83-11e8-8a2d-6796a7921dcb.png)即可正常运行。
修改后的结果：
![image](https://user-images.githubusercontent.com/13143017/49713448-b1e09180-fc83-11e8-9ac1-1977b2831427.png)

**Comment by louishua** [comment]
我也是遇到这个问题，调整顺序就可以了，希望作者更新完善一下，版本tp5.1

**Comment by xiao872380658** [comment]
亲测有用
先测试下扩展是否安装 
curl -Ss http://www.workerman.net/check.php | php

ran'ho然后修改这一处代码顺序
![image](https://user-images.githubusercontent.com/6781698/51075603-bc4ddb00-16c8-11e9-984c-40945858f4b7.png)

改成
![image](https://user-images.githubusercontent.com/6781698/51075611-df788a80-16c8-11e9-9fba-4965db5bef6e.png)
