### ISSUE TITLE
使用workerman作为http服务器启动后中间件间歇性失效

### ISSUE THREAD

**Issue by NEETLee** [top-think/think-worker#36]
php think worker 启动项目
访问绑定了中间件的控制器方法，第偶数次访问，中间件会失效
测试过路由上绑定中间件和控制器中间件，都无法正确运行

**Comment by liu21st** [comment]
什么版本？

**Comment by NEETLee** [comment]
测试过tp5.1和tp6.0
php版本7.3
复现方式：

1. 通过composer安装tp框架：composer create-project topthink/think=5.1.* tp5
2. 进入tp5根目录，通过composer安装workerman中间件：composer require topthink/think-worker=2.*
3. 使用命令行创建中间件：php think make:middleware Check
4. 在中间件中返回一个新的response，或者抛出异常
5. 在Index控制器重写`$middleware`绑定中间件
6. 使用php think worker启动项目
7. 浏览器访问index控制器，第偶数次访问会返回异常

**Comment by NEETLee** [comment]
@liu21st

**Comment by lobtao** [comment]
@ @NEETLee   composer show就能看到所有依赖包的版本号了, 没版本号, 作者不方便定位问题

**Comment by sy7600gr** [comment]
@NEETLee  您好，这个问题最后是怎么解决的呢？

**Comment by MakeHui** [comment]
@liu21st @NEETLee @sy7600gr @lobtao 
大家好，我也遇到了同样的问题，后来经过跟踪测试发现应该是由于中间件中抛出异常导致链接没有正确关闭的，第二次请求会跳过中间件继续执行，这个时候成功进入到控制器内使用正常方式返回（这时关闭了请求），再次请求会回到第一次请求的状态

这是目前知道的信息，暂时还不知道改如何改进，希望官方提供支持 🙏

**Comment by MakeHui** [comment]
基本能确定是在中间件中直接抛出异常就会出现此问题
尝试了在 `App` 中捕获中间件的异常输出，然后再以`Response`返回，问题仍然是一样的

当前的解决方法是把中间件用钩子实现，暂时运行正常
