### ISSUE TITLE
workerman不用4.0么

### ISSUE THREAD

**Issue by ken678** [top-think/think-worker#45]
workerman不用4.0么

**Comment by langyastudio** [comment]
同问

**Comment by liu21st** [comment]
4.0采用了不兼容升级 改动较大 扩展也需要重新写了

**Comment by langyastudio** [comment]
> 4.0采用了不兼容升级 改动较大 扩展也需要重新写了

什么时候能出4.0的稳定版

**Comment by langyastudio** [comment]
@liu21st  什么时候能出4.0的稳定版

**Comment by ZhangGuangHuiCoder** [comment]
现在的是不是不支持php8

**Comment by sunkangchina** [comment]
不支持4.X版本是个问题，现在安装不了。用了官方的workerman

**Comment by 18215569765** [comment]
什么时候更新下workerman4.0 谢谢

**Comment by yangguangwuwu** [comment]
什么时候更新下workerman4.0 谢谢

**Comment by yinbug** [comment]
同问，什么时候支持workerman4.0 谢谢

**Comment by henggedaren** [comment]
同问，目前版本不兼容php8.0,workerman依赖真的需要升级了。

**Comment by augushong** [comment]
think-worker还是值得去做的。目前php cli的部署方式也在流行，如果think-worker，能很好地利用workerman、swoole、reactphp等底层，还是很能打的。
